id: P008120
initial_creation_type: ocr
source_metadata:
  id: bdr:W29686
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བཤད་སྦྱར་དཀོན་མཆོག་འབྱུང་གནས
  author: ''
  volumes:
    15f5ece1580a4507bdb82ece9846a7ce:
      image_group_id: I5570
      title: ''
      volume_number: 1
      total_pages: 676
    0363c2c2ad69454a9002f5fa7b931523:
      image_group_id: I5571
      title: ''
      volume_number: 2
      total_pages: 988
ebook_metadata:
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བཤད་སྦྱར་དཀོན་མཆོག་འབྱུང་གནས
  author: ''
  sku: P008120
  cover: cover.jpg
  layers:
  - pagination
