id: P008120
initial_creation_type: ocr
source_metadata:
  id: bdr:W29686
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བཤད་སྦྱར་དཀོན་མཆོག་འབྱུང་གནས
  author: ''
  volumes:
    a24209b107234645abe7f9dad4026e2a:
      image_group_id: I5570
      title: ''
      volume_number: 1
      total_pages: 676
    eb6dc74290eb44b69c509ccca7f0561f:
      image_group_id: I5571
      title: ''
      volume_number: 2
      total_pages: 988
ebook_metadata:
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བཤད་སྦྱར་དཀོན་མཆོག་འབྱུང་གནས
  author: ''
  sku: P008120
  cover: cover.jpg
  layers:
  - pagination
