id: I0C7C1D0A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:50:09+00:00'
last_modified: '2022-06-09T04:38:36.380937+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29686
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བཤད་སྦྱར་དཀོན་མཆོག་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9AEE:
      image_group_id: I5570
      title: ''
      total_pages: 676
      order: 1
      base_file: 9AEE.txt
    44A3:
      image_group_id: I5571
      title: ''
      total_pages: 988
      order: 2
      base_file: 44A3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
